spring:
  profiles:
    active: local # "local" will use H2, anything non-"local" will use MongoDB
  application:
    name: SampleService

threadPoolSize: 1
threadCrashLimit: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  servlet:
    context-path: /rest
